development:
  adapter: postgresql
  encoding: unicode
  database: dekiru_development
  pool: 5
  username: zscott
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: dekiru_test
  pool: 5
  username: zscott
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: dekiru_production
  pool: 5
  username: zscott
  password:
