# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e3049e408f4bd6a02fa8ac9d35d796ab69f1fca9cde8b1d80ff4c54c0fab3a5e0fd4bc04738267844b81a21c8e03b70e31c8018917e1af3d4ab3ca144d93e15

test:
  secret_key_base: 3f749b7915b7a46a542eec7bd38f50d63c6461355397d9757173cdde02e14c5a1397a88cc8812f961be2c961f3a1e18978b2ef1c49f7ecf23c67fbd9347be986

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
